### ISSUE TITLE
cairo dependency problem

### ISSUE THREAD

**Issue by ljq-dmr** [rava-dosa/epub2pdf#1]
Traceback (most recent call last):
  File "D:/IdeaProjects/book2txt/mobi2pdf/mobi2pdf.py", line 2, in <module>
    from weasyprint import HTML, CSS, default_url_fetcher
  File "D:\IdeaProjects\book2txt\venv1\lib\site-packages\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "D:\IdeaProjects\book2txt\venv1\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "D:\IdeaProjects\book2txt\venv1\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "D:\IdeaProjects\book2txt\venv1\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "D:\IdeaProjects\book2txt\venv1\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "D:\IdeaProjects\book2txt\venv1\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
cannot load library 'C:\Program Files\GTK3-Runtime Win64\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

**Comment by rava-dosa** [comment]
For windows user setup process will be a bit different, try following from :-
1. https://weasyprint.readthedocs.io/en/stable/install.html#step-4-install-the-gtk-libraries
