### ISSUE TITLE
Error while trying to convert file.

### ISSUE THREAD

**Issue by shridharnator** [rava-dosa/epub2pdf#9]
`Traceback (most recent call last):
  File "epub2pdf.py", line 2, in <module>
    from weasyprint import HTML, CSS, default_url_fetcher
  File "D:\StudyMaterial\converter\converter\lib\site-packages\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "D:\StudyMaterial\converter\converter\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "D:\StudyMaterial\converter\converter\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "D:\StudyMaterial\converter\converter\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "D:\StudyMaterial\converter\converter\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "D:\StudyMaterial\converter\converter\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e`

**Comment by rava-dosa** [comment]
https://www.cairographics.org/download/
A bit late I guess, maybe for windows
